server:
    port: 9000
spring:
    profiles:
        active: dev, base-addi
    devtools:
        livereload:
            enabled: true
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:XE

        username: c##fundFun
        password: 1234

    security:
        user:
            name: user
            password: 1234
        oauth2:
            client:
                registration:
                    kakao:
                        clientId: 7d77478c4db57a767f613df7677236bd
                        scope: profile_nickname, profile_image, account_email
                        client-name: Kakao
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:9000/login/oauth2/code/kakao
                        client-authentication-method: POST
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
            # yeoooo : ? ? create ? update ?? create-drop ?? ?????
#        defer-datasource-initialization: true
        generate-ddl: true

        thymeleaf:
            cache: false
        defer-datasource-initialization: true
    # sql init script
    sql:
        init:
            platform: oracle
            encoding: UTF-8
            mode: always
custom:
    genFileDirPath: c:/Temp/fundFun


